# Generated by Django 4.2.6 on 2023-10-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
