# Generated by Django 4.2.6 on 2023-11-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userdetails_user'),
        ('authentication', '0006_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.userdetails'),
        ),
    ]
