# Generated by Django 4.2.6 on 2023-11-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_details',
        ),
    ]
