# Generated by Django 4.2.6 on 2023-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/Service_img'),
        ),
    ]
