# Generated by Django 4.2.6 on 2023-11-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_appointment_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time1',
        ),
    ]
