# Generated by Django 4.2.6 on 2023-11-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_appointment_worker_alter_appointment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
