# Generated by Django 4.2.6 on 2023-11-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
