# Generated by Django 4.2.6 on 2023-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_adminwallet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adminwallet',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
