# Generated by Django 4.2.6 on 2023-10-31 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_services_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('years_of_experience', models.IntegerField()),
                ('license_certificate', models.FileField(upload_to='licenses/')),
                ('min_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_after_one_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('street_name', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('ward', models.CharField(max_length=50)),
                ('panchayath_municipality_corporation', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
        ),
    ]
