# Generated by Django 4.2.6 on 2023-11-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_service_img'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='service',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='services',
            field=models.ManyToManyField(to='services.services'),
        ),
    ]
