# Generated by Django 4.2.6 on 2023-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='license_certificate',
            field=models.FileField(null=True, upload_to='licenses/'),
        ),
    ]
