# Generated by Django 4.2.6 on 2023-11-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userdetails_license_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='charge_after_one_hour',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='license_certificate',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='min_charge',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='services',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('worker', 'Worker')], default='user', max_length=10),
        ),
    ]
