# Generated by Django 4.2.6 on 2023-11-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_options'),
        ('users', '0006_remove_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='role',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='charge_after_one_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='license_certificate',
            field=models.FileField(null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='min_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='services',
            field=models.ManyToManyField(to='services.services'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
