# Generated by Django 4.2.6 on 2023-12-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
